### ISSUE TITLE
Impossible to use ?

### ISSUE THREAD

**Issue by HavannaFR** [tochnonement/spoly#1]
Hello, I tried to test your script, I have circles.lua and spoly.lua in a client folder and when I try for example to use your example, I get this error:

```
[hav] addons/hav/lua/autorun/client/test.lua:34: attempt to call field 'DrawOutlinedCircle' (a nil value)
  1. v - addons/hav/lua/autorun/client/test.lua:34
   2. unknown - lua/includes/modules/hook.lua:96 (x231)

```

I am missing something ?

**Comment by filipovskis** [comment]
Hello, the example is not actual. `spoly.Generate` does not return any draw function anymore, use `spoly.Draw('circle_outline_256', 0, 0, 256, 256, color_white)` https://github.com/tochnonement/spoly/blob/32f0637de3d7492c86f7c711590f2b8ab49b9cd7/spoly.lua#L156

**Comment by HavannaFR** [comment]
How nice thank you !
